In [170]:
import pandas as pd
import numpy as np
import sqlite3

In [147]:
employes = pd.read_csv("C:\\Users\\user\\Desktop\\Christine Mkhitaryan\\Data\\Raw\\employees_noisy.csv")
payroll = pd.read_csv("C:\\Users\\user\\Desktop\\Christine Mkhitaryan\\Data\\Raw\\payroll_noisy.csv")

In [148]:
employes

,EmployeeID,FirstName,LastName,Department,HireDate,Salary
0,1,John,Doe,Engineering,2018-05-15,75000
1,2,Jane,Smith,engineering,2019-03-20,68000
2,3,Mike,Johnson,SALES,2020-11-10,55000
3,4,Sarah,Williams,HR,2017-08-22,72000
4,5,NaN,Brown,ENGINEERING,2019-07-01,-5000
5,6,Robert,Taylor,engineering,03/15/2020,85000
6,7,Lisa,Anderson,Marketing,2018-12-05,NaN
7,8,David,Martinez,ENGINEERING,2025-03-30,95000
8,9,Emily,Thomas,hr,2019-09-18,60000
9,10,Christopher,Lee,Engineering,2018-01-10,0


In [149]:
payroll

,PayrollID,EmployeeID,PayPeriod,HoursWorked,Bonus,Deductions
0,1,1.0,2024-01-01,80,500,1200
1,2,2.0,2024-01-15,82,0,1100
2,3,3.0,2024-02-01,75,-100,950
3,4,4.0,2024-02-15,78,300,1300
4,5,5.0,2024-03-01,85,200,NaN
...,...,...,...,...,...,...
90,86,42.0,2024-03-15,80,250,1100
91,87,48.0,2024-05-15,84,400,1300
92,88,4.0,2024-07-01,81,300,1200
93,89,10.0,2024-09-01,83,0,1050


In [150]:
employes = employes[employes["EmployeeID"].notna() & (employes["EmployeeID"] != -1)]
employes = employes[employes["FirstName"].notna() & (employes["FirstName"] != " ") &
                    employes["LastName"].notna() & (employes["LastName"] != " ")]
employes['Department'] =employes['Department'].fillna('Unknown').str.title()


In [151]:
employes["Salary"] = pd.to_numeric(employes["Salary"], errors = 'coerce') 
employes["Salary"] = employes["Salary"].where(employes["Salary"] > 0, np.nan)
employes["Salary"] = employes["Salary"].where(employes["Salary"] <= 500000, np.nan)
emp_med = employes["Salary"].where(employes["Salary"] != np.nan).median()
emp_med
employes["Salary"] = employes["Salary"].fillna(emp_med)


In [169]:
employes["HireDate"].unique()
employes["HireDate"] = employes["HireDate"].replace("invalid date", np.nan)
employes["HireDate"]=employes["HireDate"].dropna()



In [153]:
employes.to_csv("C:\\Users\\user\\Desktop\\Christine Mkhitaryan\\Data\\Processed\\employees_clean.csv")

In [154]:
payroll

,PayrollID,EmployeeID,PayPeriod,HoursWorked,Bonus,Deductions
0,1,1.0,2024-01-01,80,500,1200
1,2,2.0,2024-01-15,82,0,1100
2,3,3.0,2024-02-01,75,-100,950
3,4,4.0,2024-02-15,78,300,1300
4,5,5.0,2024-03-01,85,200,NaN
...,...,...,...,...,...,...
90,86,42.0,2024-03-15,80,250,1100
91,87,48.0,2024-05-15,84,400,1300
92,88,4.0,2024-07-01,81,300,1200
93,89,10.0,2024-09-01,83,0,1050


In [155]:
payroll = payroll[payroll["PayrollID"].notna() & (payroll["PayrollID"] != -1) &
                  payroll["EmployeeID"].notna() & (payroll["EmployeeID"] != -1)]
payroll["HoursWorked"] = pd.to_numeric(payroll["HoursWorked"], errors = 'coerce') 
payroll["HoursWorked"] = payroll["HoursWorked"].where(payroll["HoursWorked"] > 0, np.nan)
payroll["HoursWorked"].unique()
payroll_mean = payroll["HoursWorked"].where(payroll["HoursWorked"] != np.nan).mean()
payroll["HoursWorked"]= payroll["HoursWorked"].fillna(payroll_mean)
payroll["HoursWorked"].unique()



C:\Users\user\AppData\Local\Temp\ipykernel_12276\3241348227.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  payroll["HoursWorked"] = pd.to_numeric(payroll["HoursWorked"], errors = 'coerce')
C:\Users\user\AppData\Local\Temp\ipykernel_12276\3241348227.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  payroll["HoursWorked"] = payroll["HoursWorked"].where(payroll["HoursWorked"] > 0, np.nan)
C:\Users\user\AppData\Local\Temp\ipykernel_12276\3241348227.py:7: SettingWithCopyWarning: 
A value is trying to be s

array([ 80.        ,  82.        ,  75.        ,  78.        ,
        85.        ,  88.        ,  76.        ,  90.        ,
        82.64444444,  79.        ,  81.        ,  83.        ,
        77.        ,  86.        ,  84.        ,  87.        ,
       175.        ])

In [156]:
payroll["Bonus"] = pd.to_numeric(payroll["Bonus"], errors = 'coerce') 
payroll["Bonus"] = payroll["Bonus"].where(payroll["Bonus"] > 0, 0)
payroll["Bonus"].unique()
payroll["Bonus"]= payroll["Bonus"].fillna(0)
payroll["Bonus"].unique()

C:\Users\user\AppData\Local\Temp\ipykernel_12276\3837680265.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  payroll["Bonus"] = pd.to_numeric(payroll["Bonus"], errors = 'coerce')
C:\Users\user\AppData\Local\Temp\ipykernel_12276\3837680265.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  payroll["Bonus"] = payroll["Bonus"].where(payroll["Bonus"] > 0, 0)
C:\Users\user\AppData\Local\Temp\ipykernel_12276\3837680265.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a Data

array([ 500,    0,  300,  200,  400,  250,  150,  600,  350, 1000])

In [166]:
payroll["Deductions"] = pd.to_numeric(payroll["Deductions"], errors = 'coerce') 
payroll["Deductions"] = payroll["Deductions"].where(payroll["Deductions"] > 0, np.nan)
payroll_bonus_mean = payroll["Deductions"].where(payroll["Deductions"] != np.nan).median()
payroll["Deductions"]= payroll["Deductions"].fillna(payroll_bonus_mean)
payroll["Bonus"].unique()

C:\Users\user\AppData\Local\Temp\ipykernel_12276\666930164.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  payroll["Deductions"] = pd.to_numeric(payroll["Deductions"], errors = 'coerce')
C:\Users\user\AppData\Local\Temp\ipykernel_12276\666930164.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  payroll["Deductions"] = payroll["Deductions"].where(payroll["Deductions"] > 0, np.nan)
C:\Users\user\AppData\Local\Temp\ipykernel_12276\666930164.py:4: SettingWithCopyWarning: 
A value is trying to be set on a 

array([ 500,    0,  300,  200,  400,  250,  150,  600,  350, 1000])

In [158]:

payroll_final = payroll.merge(employes[['EmployeeID', 'Salary']], on='EmployeeID', how='inner')
payroll_final.loc[payroll_final['Deductions'] > payroll_final['Salary'], 'Deductions'] = payroll_final['Salary']
payroll_validated = payroll_final.drop(columns=['Salary'])
payroll_validated.to_csv('C:\\Users\\user\\Desktop\\Christine Mkhitaryan\\Data\\Processed\\payroll_validated.csv', index=False)

In [159]:
payroll.to_csv("C:\\Users\\user\\Desktop\\Christine Mkhitaryan\\Data\\Processed\\payroll_clean.csv")

In [160]:
clean_employes = pd.read_csv("C:\\Users\\user\\Desktop\\Christine Mkhitaryan\\Data\\Processed\\employees_clean.csv")
validate_payroll = pd.read_csv("C:\\Users\\user\\Desktop\\Christine Mkhitaryan\\Data\\Processed\\payroll_validated.csv")


In [161]:
conn = sqlite3.connect("C:\\Users\\user\\Desktop\\Christine Mkhitaryan\\Data\\DB\\EmployeeManagement.db")
curs = conn.cursor()

In [162]:
clean_employes.to_sql("Employes", conn,  if_exists = "replace", index =False)
validate_payroll.to_sql("Payroll", conn, if_exists = "replace", index = False)

84

In [163]:
                   
curs.execute("DROP TABLE IF EXISTS Payroll")
curs.execute("DROP TABLE IF EXISTS SalaryHistory")
curs.execute("DROP TABLE IF EXISTS Employees")

curs.execute('''
                   CREATE TABLE Employees (
    EmployeeID INTEGER PRIMARY KEY NOT NULL,
    FirstName TEXT NOT NULL, 
    LastName TEXT NOT NULL,
    Department TEXT NOT NULL, 
    HireDate TEXT NOT NULL,
    Salary REAL NOT NULL CHECK (Salary > 0 AND Salary <= 500000))
                   ''')

curs.execute('''
             CREATE TABLE Payroll (
    PayrollID INTEGER PRIMARY KEY NOT NULL,
    EmployeeID INTEGER NOT NULL, 
    PayPeriod TEXT NOT NULL,
    HoursWorked REAL NOT NULL CHECK (HoursWorked >= 0 AND HoursWorked <= 168),
    Bonus REAL NOT NULL CHECK (Bonus >= 0),
    Deductions REAL NOT NULL CHECK (Deductions >= 0),
    FOREIGN KEY (EmployeeID) REFERENCES Employees(EmployeeID))
             ''')

curs.execute( '''
        CREATE TABLE SalaryHistory (
        HistoryID  INTEGER PRIMARY KEY AUTOINCREMENT,
        EmployeeID INTEGER NOT NULL,
        OldSalary REAL,
        NewSalary REAL NOT NULL,
        ChangeDate TEXT DEFAULT CURRENT_TIMESTAMP NOT NULL,
        FOREIGN KEY (EmployeeID) REFERENCES Employees(EmployeeID))
                  ''' )  
                   
                   

In [164]:
curs.execute(""
"DROP TRIGGER IF EXISTS LogSalaryChange;")

curs.execute("""
CREATE TRIGGER LogSalaryChange
AFTER UPDATE OF Salary ON Employees
FOR EACH ROW
WHEN OLD.Salary IS NOT NEW.Salary AND NEW.Salary IS NOT NULL
BEGIN
    INSERT INTO SalaryHistory (EmployeeID, OldSalary, NewSalary, ChangeDate)
    VALUES (OLD.EmployeeID, OLD.Salary, NEW.Salary, CURRENT_TIMESTAMP);
END;
""")

In [165]:
curs.execute("DROP VIEW IF EXISTS DepartmentPayrollSummary;")

curs.execute("""
CREATE VIEW DepartmentPayrollSummary AS
SELECT 
    e.Department,
    COUNT(DISTINCT e.EmployeeID) AS TotalEmployees,
    SUM(p.HoursWorked) AS TotalHoursWorked,
    SUM(p.Bonus) AS TotalBonus,
    AVG(DISTINCT e.Salary) AS AverageSalary
FROM Employees e
LEFT JOIN Payroll p ON e.EmployeeID = p.EmployeeID
GROUP BY e.Department;
""")

In [168]:
conn.commit()
conn.close()